### ISSUE TITLE
Can't build it on Manjaro Linux.

### ISSUE THREAD

**Issue by Rencer** [felix-lang/felix#133]
I get this error:

<pre><font color="#55FF55"><b>.o</b></font>
 * clang                 : <font color="#55FFFF"><b>build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyCommon/JudyMalloc_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudySL/JudySL_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyHS/JudyHS_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1Cascade_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1MallocIF_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1InsertBranch_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1Tables64Bit_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1Count_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1InsArray_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1Next_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1Get_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1MemUsed_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1Ins_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1CreateBranch_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1PrevEmpty_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1FreeArray_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1ByCount_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1NextEmpty_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1MemActive_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1Decascade_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/j__udy1Get_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1Prev_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1Tables32Bit_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1Del_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/Judy1/Judy1First_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLDel_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLPrevEmpty_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLCascade_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLNext_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLMemUsed_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLFreeArray_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLMallocIF_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLTables32Bit_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLInsertBranch_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLDecascade_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLCreateBranch_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLGet_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLMemActive_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/j__udyLGet_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLNextEmpty_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLIns_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLCount_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLTables64Bit_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLInsArray_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLPrev_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLByCount_dynamic.o build/release/obj/host/lib/rtl/judy_dynamic/build/release/share/src/judy/src/JudyL/JudyLFirst_dynamic.o -&gt; build/release/host/lib/rtl/libjudy_dynamic.so</b></font>
copying 4 files
cp build/release/share/src/re2/re2/re2/re2.h -&gt; build/release/share/lib/rtl/re2/re2.h
cp build/release/share/src/re2/re2/re2/set.h -&gt; build/release/share/lib/rtl/re2/set.h
cp build/release/share/src/re2/re2/re2/stringpiece.h -&gt; build/release/share/lib/rtl/re2/stringpiece.h
cp build/release/share/src/re2/re2/re2/variadic_function.h -&gt; build/release/share/lib/rtl/re2/variadic_function.h
 * clang++               : <font color="#55FF55"><b>build/release/share/src/re2/re2/util/valgrind.cc -&gt; build/release/obj/host/lib/rtl/flx_re2_static/build/release/share/src/re2/re2/util/valgrind_static.o</b></font>
 * clang++               : <font color="#55FF55"><b>build/release/share/src/re2/re2/util/strutil.cc -&gt; build/release/obj/host/lib/rtl/flx_re2_static/build/release/share/src/re2/re2/util/strutil_static.o</b></font>
 + /usr/bin/clang++ -c -std=c++14 -D_POSIX -w -fno-common -fvisibility=hidden -fno-strict-aliasing -fomit-frame-pointer -Ibuild/release/host/lib/rtl -Ibuild/release/share/lib/rtl -Ibuild/release/share/src/re2/re2 -Ibuild/release/share/src/re2/re2/util -DBUILD_RE2 -DFLX_STATIC_LINK -Wfatal-errors -Wno-invalid-offsetof -Wno-parentheses -o build/release/obj/host/lib/rtl/flx_re2_static/build/release/share/src/re2/re2/util/strutil_static.o -MMD -MF /tmp/tmpl_lr72k2/temp -Wno-sign-compare build/release/share/src/re2/re2/util/strutil.cc
In file included from build/release/share/src/re2/re2/util/strutil.cc:6:
In file included from build/release/share/lib/rtl/re2/stringpiece.h:28:
In file included from /home/szultan/felix/src/packages/regex.fdoc:493:
In file included from /home/szultan/felix/src/packages/rtl.fdoc:1409:
/home/szultan/felix/src/packages/rtl.fdoc:1435:10: fatal error: &apos;flx_rtl_config_params.hpp&apos; file not found
#include &quot;flx_rtl_config_params.hpp&quot;
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
<font color="#FF5555"><b>Error running &apos;/usr/bin/clang++ -c -std=c++14 -D_POSIX -w -fno-common -fvisibility=hidden -fno-strict-aliasing -fomit-frame-pointer -Ibuild/release/host/lib/rtl -Ibuild/release/share/lib/rtl -Ibuild/release/share/src/re2/re2 -Ibuild/release/share/src/re2/re2/util -DBUILD_RE2 -DFLX_STATIC_LINK -Wfatal-errors -Wno-invalid-offsetof -Wno-parentheses -o build/release/obj/host/lib/rtl/flx_re2_static/build/release/share/src/re2/re2/util/strutil_static.o -MMD -MF /tmp/tmpl_lr72k2/temp -Wno-sign-compare build/release/share/src/re2/re2/util/strutil.cc&apos; exited with 1</b></font>
 * clang++               : <font color="#55FF55"><b>build/release/share/src/re2/re2/util/stringprintf.cc -&gt; build/release/obj/host/lib/rtl/flx_re2_static/build/release/share/src/re2/re2/util/stringprintf_static.o</b></font>
make: *** [GNUmakefile:127: do-fbuild] Error 1
</pre>

**Comment by skaller** [comment]
Right. Sorry. The problem is that there is no definition of that file for clang/linux combination.
 So for OSX we have this:

```
~/felix>ls src/config/macosx64/
clang	gcc	rtl
```
but for linux we have this:

```
~/felix>ls src/config/linux64/
gcc	rtl
```

This is because I run OSX with clang and gcc, and build on Linux with Travis using gcc.
I'll try to fix it .. 5  minutes.

**Comment by skaller** [comment]
Fix committed but i can't test it.

**Comment by Rencer** [comment]
Thanks for the quick fix, now I don't get that error, but still can't build.
I copied the whole terminal output to pastebin, I think that is more helpful than just putting here just the error itself.
Here is the pastebin link:
[https://pastebin.com/Sfmi22v8](url)

When I looked the output I see that it said

> checking sdl-config version             : at least version 1.3 required; found 1.2.15

I searched the repos for SDL, but there is only "sdl 1.2.15-10" version in the EXTRA repository.
And there is another (in EXTRA) but that one is called  "sdl2 2.0.9-1".
These are what I find in Manjaro.
I saw that there is another issue that is about SDL (issue #125), maybe that has something to do with the error I get?

I'm not a programmer, and don't really understand what are written in the terminal when compiling from source, so I'm not sure this has anything to do with the error I get.
The previous error was gone, and it seems it is doing the compiling much longer, but still get error at some point.
Here is what exactly the error is:

<pre>DEMUX: providing LINUX EPOLL
 * clang++                             : <font color="#55FF55"><b>build/release/share/src/faio/faio_posixio.cpp -&gt; build/release/obj/host/lib/rtl/faio_static/build/release/share/src/faio/faio_posixio_static.o</b></font>
 * clang++                             : <font color="#55FF55"><b>build/release/share/src/faio/faio_timer.cpp -&gt; build/release/obj/host/lib/rtl/faio_static/build/release/share/src/faio/faio_timer_static.o</b></font>
 * ar                                  : <font color="#55FFFF"><b>build/release/obj/host/lib/rtl/faio_static/build/release/share/src/faio/faio_timer_static.o build/release/obj/host/lib/rtl/faio_static/build/release/share/src/faio/faio_posixio_static.o -&gt; build/release/host/lib/rtl/libfaio_static.a</b></font>
 * ranlib                              : <font color="#55FFFF"><b>build/release/host/lib/rtl/libfaio_static.a</b></font>
 * clang++                             : <font color="#55FF55"><b>build/release/share/src/faio/faio_posixio.cpp -&gt; build/release/obj/host/lib/rtl/faio_dynamic/build/release/share/src/faio/faio_posixio_dynamic.o</b></font>
 * clang++                             : <font color="#55FF55"><b>build/release/share/src/faio/faio_timer.cpp -&gt; build/release/obj/host/lib/rtl/faio_dynamic/build/release/share/src/faio/faio_timer_dynamic.o</b></font>
 * clang++                             : <font color="#55FFFF"><b>build/release/obj/host/lib/rtl/faio_dynamic/build/release/share/src/faio/faio_timer_dynamic.o build/release/obj/host/lib/rtl/faio_dynamic/build/release/share/src/faio/faio_posixio_dynamic.o demux_dynamic flx_pthread_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_async_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_pthread_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_pthread_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic -&gt; build/release/host/lib/rtl/libfaio_dynamic.so</b></font>
 * clang++                             : <font color="#55FF55"><b>build/release/share/src/flx_drivers/flx_arun_lib_dynamic.cpp -&gt; build/release/obj/host/bin/flx_arun/build/release/share/src/flx_drivers/flx_arun_lib_dynamic_dynamic.o</b></font>
 * clang++                             : <font color="#55FF55"><b>build/release/share/src/flx_drivers/flx_arun_main.cxx -&gt; build/release/obj/host/bin/flx_arun/build/release/share/src/flx_drivers/flx_arun_main_dynamic.o</b></font>
 * clang++                             : <font color="#55FFFF"><b>build/release/obj/host/bin/flx_arun/build/release/share/src/flx_drivers/flx_arun_main_dynamic.o build/release/obj/host/bin/flx_arun/build/release/share/src/flx_drivers/flx_arun_lib_dynamic_dynamic.o faio_dynamic demux_dynamic flx_pthread_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_async_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_pthread_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_pthread_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic demux_dynamic flx_pthread_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_async_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_pthread_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_pthread_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_exceptions_dynamic flx_async_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_pthread_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_dynlink_dynamic flx_gc_dynamic flx_exceptions_dynamic judy_dynamic flx_strutil_dynamic flx_strutil_dynamic flx_uint256_t_dynamic -&gt; build/release/host/bin/flx_arun</b></font>
[fbuild] [Felix] COMPILING TOOLS
Traceback (most recent call last):
  File &quot;fbuild/fbuild-light&quot;, line 11, in &lt;module&gt;
    main()
  File &quot;/home/szultan/felix/fbuild/lib/fbuild/main.py&quot;, line 179, in main
    result = build(ctx)
  File &quot;/home/szultan/felix/fbuild/lib/fbuild/main.py&quot;, line 104, in build
    target.function(ctx)
  File &quot;/home/szultan/felix/fbuildroot.py&quot;, line 631, in build
    compilers.flxg, phases.target.cxx.static, drivers)
  File &quot;/home/szultan/felix/fbuild/lib/fbuild/functools.py&quot;, line 32, in call
    return import_function(function)(*args, **kwargs)
  File &quot;/home/szultan/felix/fbuild/lib/fbuild/functools.py&quot;, line 24, in import_function
    return getattr(__import__(m, {}, {}, [&apos;&apos;]), f)
  File &quot;/home/szultan/felix/buildsystem/flx.py&quot;, line 164
    def link_exe(self, *args, async=False, macros=[], objects=[], **kwargs):
                                  ^
SyntaxError: invalid syntax
make: *** [GNUmakefile:127: do-fbuild] Error 1</pre>

But I think it is better to look at the whole terminal output on that pastebin, that is defenitely more helpful in figuring out the problem and fixing it.

Thanks, again!

**Comment by kirbyfan64** [comment]
Ack, right, Python 3.7 made async a keyword...

**Comment by skaller** [comment]
But that's been fixed hasn't it? This is not a new error. I think that only fbuild got fixed tho, not the Felix version of fbuild. I don't think fbuild head actually works with Felix. in any case Python 3.6.* works.

**Comment by kirbyfan64** [comment]
@skaller The error is coming from code in the buildsystem directory, not from Fbuild.

**Comment by skaller** [comment]
So its local to one file? I just search/replaced it .. doing a build now. Will commit if it works, but i have Python 3.6 so its hard to say.

**Comment by loftsmen** [comment]
Manjaro is based of ArchLinux, which builds from https://github.com/felix-lang/felix/commit/d78b7388478debfb59e6c58491dbfa7fc5a90bdd.

As mentioned, SDL2 errors are in optional components. Can confirm SDL2 errors are benign to the build on ArchLinux. I surmise it is the same on Manjaro.

**Comment by Rencer** [comment]
Still can't build it on Manjaro, so why you guys closed it when this is not fixed???

Get this after AN HOUR of compiling:
`FLX_INSTALL_DIR=build/release build/release/host/bin/flx --felix=build.fpc \
	--usage=prototype --expect --input --nonstop \
	--indir=build/release/test/tutopt --regex='.*\.flx' build/release/test/tutopt
Processing 10 files
Processing [01/10]: mmap_01.flx
[FlxPkg:map_package_requirements] Error 1 executing flx_pkgconfig, args=list('--path+=build/release/host/config', '--path+=/usr/local/lib/felix/packages/host/config', '--field=cflags', '--keepleftmost', '@/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/mmap_01.resh')
BATCH MODE ERROR HANDLER
Processing [02/10]: sdlgui/gui_01_window_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.includes:6:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.includes:6:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_01_window_01_dynamic.o" FAILED
Processing [03/10]: sdlgui/gui_02_font_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_02_font_01_dynamic.o" FAILED
Processing [04/10]: sdlgui/gui_03_draw_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_03_draw_01_dynamic.o" FAILED
Processing [05/10]: sdlgui/gui_04_wm_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_04_wm_01_dynamic.o" FAILED
Processing [06/10]: sdlgui/gui_05_window_controller_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_05_window_controller_01_dynamic.o" FAILED
Processing [07/10]: sdlgui/gui_06_button_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_06_button_01_dynamic.o" FAILED
Processing [08/10]: sdlgui/gui_07_editfield_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_07_editfield_01_dynamic.o" FAILED
Processing [09/10]: sdlgui/gui_08_menu_01.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_01_dynamic.o" FAILED
Processing [10/10]: sdlgui/gui_08_menu_02.flx
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-MM" "-D_POSIX" "-std=gnu++14" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.cpp" FAILED
[flx_depchk] C++ Dependency generator FAILED on /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.cpp
In file included from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.hpp:13,
                 from /home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.cpp:6:
/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.includes:7:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
C++ command="g++" "-fPIC" "-fvisibility=hidden" "-D_GLIBCXX_USE_CXX11_ABI=1" "-D_POSIX" "-g" "-c" "-O1" "-fno-common" "-fno-strict-aliasing" "-std=gnu++14" "-w" "-Wfatal-errors" "-Wno-invalid-offsetof" "-Wno-parentheses" "-Wno-unused-variable" "-Wno-unused-label" "-Wno-unused-function" "-Wno-sign-compare" "-Wno-missing-braces" "-I/usr/local/include/SDL2" "-Ibuild/release/share/lib/rtl" "-Ibuild/release/host/lib/rtl" "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02.cpp" -o "/home/gofri/.felix/cache/text/home/gofri/felix/build/release/test/tutopt/sdlgui/gui_08_menu_02_dynamic.o" FAILED
Batch result (00 OK + 10 FAIL)/10
Error 1 in flx: [strerror_r] Failed to find text for error number 1
make: [GNUmakefile:338: tutopt-check] Error 1 (ignored)
build/release/host/bin/flx --felix=build.fpc --usage=prototype --expect --nonstop --indir=build/release/test/extras --regex='.*\.flx' build/release/test
Processing 1 files
Processing [01/01]: gmp-01.flx
Opening syntax extensions /home/gofri/felix/src/packages/gmp.fdoc: line 199, cols 1 to 24
Parsed open of syntax extensions gmp_syntax
Batch result (01 OK + 00 FAIL)/ 1`

**Comment by Rencer** [comment]
I have SDL2 installed  on my Manjaro, but STILL CAN'T compile Felix.
Because you closed this UNSOLVED issue, I opened a new one.
When it will be fixed, so those who have Arch-based linux, can use this program?
